
TRUNCATE TABLE  embedded_law_references RESTART IDENTITY;
TRUNCATE TABLE  extraction_metadata RESTART IDENTITY;
TRUNCATE TABLE  external_links RESTART IDENTITY;
TRUNCATE TABLE  modified_articles RESTART IDENTITY;
TRUNCATE TABLE  footnote_references RESTART IDENTITY;
TRUNCATE TABLE  document_modified_by RESTART IDENTITY;
TRUNCATE TABLE  document_modifies RESTART IDENTITY;
TRUNCATE TABLE  footnotes RESTART IDENTITY;
TRUNCATE TABLE  article_contents RESTART IDENTITY;
TRUNCATE TABLE  document_versions RESTART IDENTITY;
TRUNCATE TABLE  hierarchy_elements ;
TRUNCATE TABLE  documents RESTART IDENTITY;